theme: jekyll-theme-chirpy
lang: zh-CN
timezone: Asia/Shanghai
title: 筑梦之旅
tagline: 属于你的e，记录生活感悟、技术笔记与随想碎片。
description: 在这里记录生活感悟、技术笔记与随想碎片。
url: https://zhuzhubaby00.github.io
github:
  username: zhuzhubaby00
twitter:
  username: 
social:
  name: zhuzhu
  email: 2651910270@qq.com
  fediverse_handle: 
  links:
  - https://github.com/zhuzhubaby00
webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
  baidu: 
  facebook: 
analytics:
  google:
    id: 
  goatcounter:
    id: 
  umami:
    id: 
    domain: 
  matomo:
    id: 
    domain: 
  cloudflare:
    id: 
  fathom:
    id: 
pageviews:
  provider: 
theme_mode: 
cdn: 
avatar: /assets/img/avatar.jpg
social_preview_image: 
toc: true
comments:
  provider: giscus
  active: giscus
  giscus:
    repo: zhuzhubaby00/zhuzhubaby00.github.io
    repo_id: R_kgDOUJzndg
    category: Announcements
    category_id: DIC_kwDOUJznds4DE11I
    mapping: pathname
    strict: 0
    input_position: bottom
    lang: zh-CN
    reactions_enabled: 1
  utterances:
    repo: 
    issue_term: 
assets:
  self_host:
    enabled: 
    env: 
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths: 
paginate: 10
baseurl: ''
kramdown:
  footnote_backlink: '&#8617;&#xfe0e;'
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
collections:
  tabs:
    output: true
    sort_by: order
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
    toc: true
    permalink: /posts/:title/
- scope:
    path: _drafts
  values:
    comments: false
- scope:
    path: ''
    type: tabs
  values:
    layout: page
    permalink: /:title/
sass:
  style: compressed
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs:
    - development
exclude:
- '*.gem'
- '*.gemspec'
- docs
- tools
- README.md
- LICENSE
- purgecss.js
- '*.config.js'
- package*.json
jekyll-archives:
  enabled:
  - categories
  - tags
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
reading_time: true
